# Generated by Django 2.0.7 on 2018-07-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=250, verbose_name='재료 별 HASH 값')),
                ('name', models.CharField(max_length=30, verbose_name='술 이름')),
                ('gens', models.IntegerField(verbose_name='Gens')),
                ('price', models.FloatField(verbose_name='ETH 가격')),
                ('created', models.DateTimeField(verbose_name='생성 시간')),
                ('imgs', models.ImageField(upload_to='ing/', verbose_name='재료 이미지')),
            ],
        ),
    ]
