# Generated by Django 2.0.7 on 2018-07-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180714_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='market_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='술 이름(영어)')),
                ('imgs', models.ImageField(upload_to='image/', verbose_name='이미지 파일')),
            ],
        ),
    ]
