# Generated by Django 2.0.7 on 2018-07-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_market_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_img',
            name='description',
            field=models.CharField(default='맛있는술', max_length=250, verbose_name='술 설명'),
        ),
    ]
