# Generated by Django 2.0.7 on 2018-07-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_market_img_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_img',
            name='types',
            field=models.CharField(default='alcohol', max_length=200, verbose_name='필터 타입'),
        ),
    ]
