# Generated by Django 2.0.7 on 2018-08-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_market_img_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_img',
            name='bg_color',
            field=models.CharField(default='#', max_length=200, verbose_name='배경색'),
        ),
    ]
