# Generated by Django 2.0.7 on 2018-08-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_market_img_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_img',
            name='img_index',
            field=models.CharField(default=0, max_length=255, verbose_name='이미지 인덱스 번호'),
        ),
    ]
