# Generated by Django 2.0.7 on 2018-08-02 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_market_img_bg_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='make_sul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sul_jan', models.CharField(max_length=250, verbose_name='술잔 모양, st 존재시, 세모모양 제외')),
                ('gradient', models.BooleanField(default=False, verbose_name='음료색 그라디언트')),
                ('css', models.CharField(max_length=250, verbose_name='음료 색상, css 코드')),
                ('is_st', models.BooleanField(default=False, verbose_name='건더기 유무')),
                ('st1', models.CharField(default='none', max_length=250, verbose_name='건더기1')),
                ('st2', models.CharField(default='none', max_length=250, verbose_name='건더기2')),
                ('is_ice', models.BooleanField(default=False, verbose_name='아이스크림 유무')),
                ('ice', models.CharField(max_length=250, verbose_name='아이스크림 코드')),
                ('bg_color', models.CharField(max_length=100, verbose_name='음료 배경색')),
                ('headache', models.CharField(default='%', max_length=250, verbose_name='숙취도 수치')),
                ('degreeOfPig', models.CharField(default='Kcal', max_length=250, verbose_name='비만도 수치')),
                ('specials_name', models.CharField(max_length=250, verbose_name='특수 능력치')),
                ('specials', models.CharField(max_length=250, verbose_name='특수 능력치 수치')),
                ('market_img', models.ManyToManyField(to='market.market_img', verbose_name='재료들')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='특수 능력치')),
            ],
        ),
    ]
