# Generated by Django 2.0.7 on 2018-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_cat_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_fin_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='고양이 대사')),
            ],
        ),
    ]
