# Generated by Django 2.0.7 on 2018-08-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180803_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_sul',
            name='desc',
            field=models.CharField(default='스윙스 땀 맛이나는 음료가 생성되었다!', max_length=250, verbose_name='설명 랜덤'),
        ),
    ]
