# Generated by Django 2.0.7 on 2018-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_make_sul_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='fin_sul_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='마지막 술 설명')),
            ],
        ),
    ]
