# Generated by Django 2.0.7 on 2018-08-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_fin_sul_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_sul',
            name='sul_name',
            field=models.CharField(default='폭풍의 ', max_length=250, verbose_name='술이름'),
        ),
    ]
